
# Application name (optional)
spring.application.name=spring-boot_Pro

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/testingpro


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Server port (optional)
server.port=8080


